import Head from 'next/head'
import React from 'react'

type Props = {}

function Header({}: Props) {
  return (
    <div className="container max-w-5xl mx-10">
      <Head>
        <title>Turborepo Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-2xl font-bold">Merkezsoft</h1>
    </div>
  )
}

export default Header
